security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /main
                failure_path: /login

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/main, roles: ROLE_USER }
